name: docker
description: Docker/Podman container management skill
version: "1.0.0"

provides:
  - list_containers
  - list_images
  - run_container
  - stop_container
  - pull_image
  - build_image
  - exec_command
  - logs

requires_capabilities:
  - exec.docker
  - filesystem.read
  - filesystem.write
